### ISSUE TITLE
Add fold_left function?

### ISSUE THREAD

**Issue by Th0rgal** [onlydustxyz/cairo-streams#20]
Hey there,

I've been playing with Ocaml this year and there was a cool function called ``fold_left`` and I thought it could be cool to add it.
Here is the fold_left signature:
fold_left : function, acc, array -> new_acc
And the function signature:
function : acc_type, array_elt_type -> acc_type

It allows you to apply function to acc (the accumulator) and the first element of the array to get the new acc. It will continue until the end of the array from left to right. This makes it possible to perform many other functions easily. To create a function that adds all the elements of a list, simply pass an add function that sums two elements.

I built a version working with felts only. 
```cairo
    func fold_left{range_check_ptr}(
        function : codeoffset, acc : felt, args_len : felt, args : felt*
    ) -> (acc : felt):
        let (func_pc) = get_label_location(function)
        return _fold_left(func_pc, acc, args_len, args)
    end

    func _fold_left{range_check_ptr}(func_pc : felt, acc : felt, args_len : felt, args : felt*) -> (
        acc : felt
    ):
        if args_len == 0:
            return (acc)
        end
        [ap] = acc; ap++
        [ap] = [args]; ap++
        call abs func_pc
        return _fold_left(func_pc, [ap - 1], args_len - 1, args + 1)
    end
```

Here is an example usage (a protostar test):
```cairo
func sum{syscall_ptr : felt*, range_check_ptr, pedersen_ptr : HashBuiltin*}(
    acc : felt, value : felt
) -> (output : felt):
    return (acc + value)
end

@view
func test_fold_left{syscall_ptr : felt*, range_check_ptr, pedersen_ptr : HashBuiltin*}():
    let (arr : felt*) = alloc()
    assert arr[0] = 5
    assert arr[1] = 4
    assert arr[2] = 3
    assert arr[3] = 2
    assert arr[4] = 1
    let (result) = List.fold_left(sum, 0, 5, arr)
    assert result = 15
    return ()
end
```

I am afraid that to use structs one loses in efficiency. What do you think?

**Comment by ofux** [comment]
Hi, thanks for submitting the issue.

What is the difference between `fold-left` and `reduce` the way it is implemented [here](https://github.com/onlydustxyz/cairo-streams/blob/main/src/onlydust/stream/internal/reduce.cairo)?

**Comment by Th0rgal** [comment]
Well, it looks like I should have taken a better look at what this function did before opening this exit. It's the same thing :P
